sudo: required
services:
  - docker


before_install:
  - docker build -t yaserhesham/docker-react-proj -f Dockerfile.dev .

script:
  - docker run -e CI=true yaserhesham/docker-react-proj npm run test